// Exercise actual gallery selection with multiple dates, versions and catalog aliases.
const {readFileSync} = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = readFileSync(require('node:path').join(__dirname, '../web/app.js'), 'utf8');
const context = vm.createContext({URLSearchParams, document: {querySelector() { return {}; }}});
vm.runInContext(source.slice(0, source.indexOf('$("#search").addEventListener')), context);
function run(code) { return vm.runInContext(code, context); }
run(`
function photo(id, category, date, device, extra = {}) {
  return {id, category, capturedAt: date, captureDate: date, device, kind: "photo", name: id, extension: "jpg", tags: [], ...extra};
}
state.items = [photo('old', 'M 31', '2026-01-01', 'S50'), photo('new', 'M 31', '2026-06-01', 'S30')];
state.editedItems = [photo('edited', 'M 31', '2026-06-02', 'S30', {isEdited: true})];
`);
assert.equal(run('visibleItems()[0].id'), 'edited');
run('state.filters.device = "S50"');
assert.equal(run('visibleItems()[0].id'), 'old', 'filter before auto preference and merging');
run('state.filters.device = "all"; state.filters.dateTo = "2026-01-02"');
assert.equal(run('visibleItems()[0].id'), 'old', 'older capture remains discoverable');
run('state.filters.dateTo = ""; state.items[0].tags = ["窄带"]; state.query = "窄带"');
assert.equal(run('visibleItems()[0].id'), 'old', 'search includes tags');
run('state.query = ""; state.workflows = {"M 31": {favorite: true, stage:"processing", notes:"去梯度"}}; state.query = "去梯度"');
assert.equal(run('visibleItems().length'), 1, 'search includes notes');
run('state.query = ""; state.workspace = "favorites"');
assert.equal(run('visibleItems().length'), 1);
run('state.workspace = "done"');
assert.equal(run('visibleItems().length'), 0);
run('state.workflows["SH2-103"] = {favorite:true, stage:"done", notes:""}');
assert.equal(run('workflow({category:"SH2-103"}).favorite'), true);
assert.equal(run('workflow({category:"SH2-157"}).favorite'), false);
run('state.workspace = "all"; state.editedItems = []; state.filters.target = "recent"; state.items = Array.from({length:12}, (_,i) => photo(String(i), String(i), `2026-01-${String(i+1).padStart(2,"0")}`, "S30"))');
assert.equal(run('visibleItems()[0].id'), '11', 'recent captures sorted before limiting');
assert.equal(run('visibleItems().length'), 10);
run(`state.filters.target = "all"; state.items = [photo('jpg', 'M 31', '2026-06-01', 'S30'), photo('fit', 'M 31', '2026-01-01', 'S50', {kind:'raw', extension:'fit'})]; state.editedItems = [photo('edit', 'M 31', '2026-07-01', 'S30', {isEdited:true})]`);
assert.equal(run('visibleItems()[0].id'), 'fit', 'FIT takes priority over JPG and edits');
run('state.filters.device = "S30"');
assert.equal(run('visibleItems()[0].id'), 'edit', 'filter applies before FIT preference');
run('state.filters.device = "all"; state.galleryMode = "edited"');
assert.equal(run('visibleItems()[0].id'), 'edit', 'explicit edited mode is preserved');
run('state.galleryMode = "source"');
assert.equal(run('visibleItems()[0].id'), 'fit');
run('state.mergeTargets = false');
assert.equal(run('visibleItems().length'), 2, 'unmerged source mode exposes both formats');
assert.equal(run('sortedItems(visibleItems())[0].id'), 'fit', 'FIT sorted first');
run('state.query = "jpg"');
assert.equal(run('visibleItems()[0].id'), 'jpg', 'JPG remains searchable');
run('state.query = ""; state.items = state.items.filter(item => item.kind === "raw"); state.editedItems = []; state.galleryMode = "auto"');
assert.equal(run('visibleItems()[0].id'), 'fit', 'FIT-only library survives JPG cleanup');
run(`const rawPreview = {id: 'M31/test.fit', kind:'raw', url:'/api/fits-preview/M31/test.fit?v=123'}; state.settings = {source:'/one'};`);
assert.match(run('previewUrl(rawPreview)'), /v=123&mode=auto&black=0&brightness=0&neutralize=0/);
run('state.fitsOptions.set(fitsOptionKey(rawPreview), {mode:"linear",black:1,brightness:0.5,neutralize:true})');
assert.match(run('previewUrl(rawPreview)'), /mode=linear&black=1&brightness=0.5&neutralize=1/);
assert.equal(run('rawPreview.url'), '/api/fits-preview/M31/test.fit?v=123', 'adjustment never mutates original URL');
run('state.settings.source = "/two"');
assert.match(run('previewUrl(rawPreview)'), /mode=auto/, 'different libraries do not share adjustments');
assert.equal(run('previewUrl({kind:"photo",url:"/media/test.jpg"})'), '/media/test.jpg');
run(`state.galleryMode = "auto"; state.mergeTargets = true; state.filters = {target:"all",device:"all",tag:"all",rating:"all",dateFrom:"",dateTo:"",sort:"capture_desc"};
state.items = [photo('fit-new','M31','2026-06-01','S50',{kind:'raw',rating:1}),photo('jpg-old','M31','2026-01-01','S50',{rating:5}),photo('m42','M42','2026-05-01','S50',{rating:3}),photo('unrated','M8','2026-07-01','S50')];`);
assert.equal(run('visibleItems().find(i=>i.category==="M31").id'), 'fit-new', 'default retains FIT priority');
run('state.filters.rating="4"');
assert.equal(run('visibleItems().map(i=>i.id).join(",")'), 'jpg-old', 'score filtering precedes version preference and merge');
run('state.filters.rating="0"');
assert.equal(run('visibleItems().map(i=>i.id).join(",")'), 'unrated');
run('state.filters.rating="all"; state.filters.sort="rating_desc"');
assert.equal(run('sortedItems(visibleItems()).map(i=>i.id).join(",")'), 'jpg-old,m42,unrated', 'explicit score sort selects best rated representative');
run('state.filters.sort="rating_asc"');
assert.equal(run('sortedItems(visibleItems()).map(i=>i.id).join(",")'), 'fit-new,m42,unrated', 'unrated remains last even ascending');
run('state.mergeTargets=false; state.filters.sort="rating_desc"');
assert.equal(run('sortedItems(visibleItems()).map(i=>i.id).join(",")'), 'jpg-old,m42,fit-new,unrated');
assert.equal(run('photoRating({rating:undefined})'), 0);
assert.equal(run('photoRating({rating:6})'), 0);
assert.match(run('ratingEditor({rating:4})'), /aria-label="4 星" aria-pressed="true"/);
run(`state.items = []; state.editedItems = [photo('final-m31', 'M 31', '2026-09-01', '后期导出', {isEdited:true,tags:['精选']}), photo('final-m42', 'M 42', '2026-09-02', '后期导出', {isEdited:true,tags:['精选']})];
state.galleryMode = 'edited'; state.workspace = 'all'; state.query = ''; state.filters = {target:'all',device:'all',tag:'all',rating:'all',dateFrom:'',dateTo:'',sort:'capture_desc'};`);
assert.equal(run('visibleItems().length'), 2, 'finished pictures work without any originals');
assert.equal(run('galleryFacets().targets.map(i=>i.value).join(",")'), 'M 31,M 42', 'finished-only target filter contains its own targets');
assert.equal(run('galleryFacets().devices[0].value'), '后期导出');
assert.equal(run('galleryFacets().tags[0].count'), 2);
run("state.filters.target='M 42'; state.filters.tag='精选'");
assert.equal(run('visibleItems()[0].id'), 'final-m42', 'finished-only target and tag filtering works');
run("state.filters.target='all';state.filters.tag='all';state.galleryMode='source'");
assert.equal(run('visibleItems().length'), 0, 'finished pictures never become raw library items');
assert.equal(run('galleryFacets().targets.length'), 0, 'switching back to originals removes finished-only facets');
run(`const accessNodes = {}; document.querySelector = id => accessNodes[id] ||= {};
state.sourceStatus = {accessible:false,mediaCount:0}; state.editedStatus = {accessible:true,mediaCount:2};
state.galleryMode='edited';renderAccess();`);
assert.equal(run('accessNodes["#access-banner"].hidden'), true, 'offline originals do not block finished gallery');
run("state.galleryMode='source';renderAccess()");
assert.equal(run('accessNodes["#access-banner"].hidden'), false, 'original mode still explains offline source');
run("state.galleryMode='auto';renderAccess()");
assert.equal(run('accessNodes["#access-banner"].hidden'), true, 'available finished pictures remain browseable in automatic mode');
console.log('Gallery regressions: 43 assertions passed.');
